// Deliberate breaks of the demo app, one per rule worth protecting.
// `npm run mutate` applies each, runs the tests covering it, and expects a failure.
// When a test generated by the agents can't catch its break, the test is too weak.

import { defineMutations } from '../kit/observe/mutations.ts';

const SERVER = 'examples/demo-app/server.mjs';
const APP = 'examples/demo-app/public/app.js';

export default defineMutations([
  {
    id: 'lists-not-private',
    covers: 'errands#private-lists',
    description: "the server returns every user's errands",
    edits: [{ file: SERVER, find: '.filter((e) => e.owner === email)', replace: '.filter(() => true)' }],
  },
  {
    id: 'blank-titles-saved',
    covers: 'errands#no-blank-titles',
    description: 'the server saves errands with a blank title',
    edits: [{ file: SERVER, find: "if (!title) return send(res, 422, { error: 'title_required' });", replace: '' }],
  },
  {
    id: 'counter-always-plural',
    covers: 'errands#remaining-counter',
    description: 'the counter says "1 errands left"',
    edits: [{ file: APP, find: "left === 1 ? '1 errand left'", replace: "false ? '1 errand left'" }],
  },
  {
    id: 'done-not-saved',
    covers: 'errands#done-persists',
    description: 'ticking an errand off is never saved',
    edits: [
      { file: SERVER, find: 'errand.done = Boolean((await readJson(req)).done);', replace: 'await readJson(req);' },
    ],
  },
  {
    id: 'delete-does-nothing',
    covers: 'errands#delete-errand',
    description: 'deleting an errand answers 204 but keeps it',
    edits: [{ file: SERVER, find: '    errands.delete(errand.id);\n', replace: '' }],
  },
  {
    id: 'sign-out-keeps-session',
    covers: 'sign-in#server-sign-out',
    description: 'sign-out clears the cookie but the server session lives on',
    edits: [{ file: SERVER, find: 'if (sid) sessions.delete(sid);', replace: '' }],
  },
  {
    id: 'unknown-email-revealed',
    covers: 'sign-in#generic-error',
    description: 'an unknown email gets its own "No account" message',
    edits: [
      {
        file: SERVER,
        find: "if (!user || user.password !== password) return send(res, 401, { error: 'invalid_credentials' });",
        replace:
          "if (!user) return send(res, 404, { error: 'no_account' });\n    if (user.password !== password) return send(res, 401, { error: 'invalid_credentials' });",
      },
      {
        file: APP,
        find: "if (!res.ok) return renderLogin('Wrong email or password.');",
        replace:
          "if (res.status === 404) return renderLogin('No account with that email.');\n  if (!res.ok) return renderLogin('Wrong email or password.');",
      },
    ],
  },
  {
    id: 'email-case-sensitive',
    covers: 'sign-in#edge:email-case',
    description: 'sign-in only works with the email in the exact case it was registered',
    edits: [
      { file: SERVER, find: "users.get(String(email ?? '').toLowerCase())", replace: "users.get(String(email ?? ''))" },
    ],
  },
  {
    id: 'private-page-open',
    covers: 'sign-in#private-pages',
    description: 'the errand page no longer sends signed-out visitors to the login page',
    edits: [
      { file: APP, find: "if (!me.ok) return void (location.hash = '#/login');", replace: 'if (!me.ok) return;' },
    ],
  },
  {
    id: 'empty-fields-submitted',
    covers: 'sign-in#edge:empty-fields',
    description: 'the login form no longer requires email and password',
    edits: [
      { file: APP, find: "autocomplete: 'username', required: true", replace: "autocomplete: 'username'" },
      {
        file: APP,
        find: "autocomplete: 'current-password',\n      required: true,",
        replace: "autocomplete: 'current-password',",
      },
    ],
  },
]);
